name: CI

on: [push, pull_request]

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for tab characters
      run: "! grep -P -R '\\t' src/"
